### ISSUE TITLE
AttributeError in parse_dysymtab

### ISSUE THREAD

**Issue by rammy22** [aaronst/macholibre#11]
``` python
Could not parse file: /sample/01f6269609707284a591b2a31a2f36329b78e2adc02f46573ab33caf21edf698
ERROR:root:Traceback (most recent call last):
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 67, in main
    parse(args.input[0], f=args.output)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 41, in parse
    p.parse_file()
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 814, in parse_file
    endi=identity[1], size=self.get_file_size()))
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 746, in parse_macho
    lc.parse_lcs()
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/loadcommander.py", line 554, in parse_lcs
    self.parse_dysymtab(lc)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/loadcommander.py", line 244, in parse_dysymtab
    self.macho.symtab.il = little(il, 'I')
AttributeError: 'NoneType' object has no attribute 'il'
```

**Comment by aaronst** [comment]
This is now fixed.
