### ISSUE TITLE
KeyError in list_macho_flags

### ISSUE THREAD

**Issue by rammy22** [aaronst/macholibre#13]
``` python
Could not parse file: /sample/1824ed42581e489a7e916faf9f3967ef77844e6775cd29c87ff6ac314ebca0fc
ERROR:root:Traceback (most recent call last):
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 67, in main
    parse(args.input[0], f=args.output)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 41, in parse
    p.parse_file()
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 814, in parse_file
    endi=identity[1], size=self.get_file_size()))
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 736, in parse_macho
    flags = self.list_macho_flags(flags)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 90, in list_macho_flags
    l.append(dictionary.flags[2 ** j])
KeyError: 67108864
```

**Comment by aaronst** [comment]
@rammy22 Opening this up in a hex editor, this doesn't appear to be a mach-o file at all.  Trying to think of a good solution to reject these files that use mach-o magic values but aren't actually mach-o's...

**Comment by aaronst** [comment]
I added some more checks to the earlier stages of parsing.  It handles this case.
