### ISSUE TITLE
Error parsing headers in universal files

### ISSUE THREAD

**Issue by sjc** [aaronst/macholibre#19]
```Traceback (most recent call last):
  File "./macho.py", line 98, in <module>
    json_data = parse(file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholibre/__init__.py", line 45, in parse
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholibre/parser.py", line 1701, in parse
    self.parse_file()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholibre/parser.py", line 1687, in parse_file
    self.parse_universal()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholibre/parser.py", line 1655, in parse_universal
    identity = self.identify_file()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/macholibre/parser.py", line 135, in identify_file
    magic))
ValueError: Provided file has unrecognized magic: 12
```

The errors appear to be in the loop inside `parse_universal()`:

* Should seek to `offset` before calling `identify_file()` at line 1646 so `__file` is pointing to the start of the Mach Header
* On return from `identify_file()`, should restore the previous file position and then read another 4 bytes (to skip over `align`) to be in position to read the next section of the Fat Header during the next iteration

**Comment by aaronst** [comment]
Whoops, sorry about that.  I had that all messed up.  Should be fixed now.
