### ISSUE TITLE
Symbol not found when running on OS X

### ISSUE THREAD

**Issue by L45eMy** [aaronst/macholibre#2]
I’m trying to get macholibre working on OS X (already works fine on Ubuntu).

I followed the instructions and installed the latest ctypescrypto from GitHub, before installing macholibre via pip. However I’m still getting the following error when `from macholibre import macholibre`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/macholibre/macholibre.py", line 27, in <module>
    from parser import Parser
  File "/Library/Python/2.7/site-packages/macholibre/parser.py", line 30, in <module>
    from ctypescrypto import cms, oid
  File "/Library/Python/2.7/site-packages/ctypescrypto/cms.py", line 18, in <module>
    from ctypescrypto.x509 import StackOfX509
  File "/Library/Python/2.7/site-packages/ctypescrypto/x509.py", line 13, in <module>
    from ctypescrypto.pkey import PKey
  File "/Library/Python/2.7/site-packages/ctypescrypto/pkey.py", line 310, in <module>
    libcrypto.EVP_PKEY_print_public.argtypes = (c_void_p, c_void_p, c_int, c_void_p)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7f8fbb424110, EVP_PKEY_print_public): symbol not found
```

Any hint?

**Comment by aaronst** [comment]
Hi @L45eMy,

What version of openssl do you have installed?

`openssl version`

**Comment by L45eMy** [comment]
Hello @aaronst,

I've been testing on Mavericks with `OpenSSL 1.0.1h 5 Jun 2014` and El Capitan with `OpenSSL 0.9.8zh 14 Jan 2016`.

**Comment by aaronst** [comment]
Try updating openssl with brew.  I'm running successfully on El Capitan with `OpenSSL 1.0.2h`

```
brew update
brew install openssl
brew link --force openssl
```

**Comment by L45eMy** [comment]
Thank you very much, that did it.

**Comment by aaronst** [comment]
@L45eMy awesome! 😄 

Hope the library works well for you, let me know if you run into any more issues or have a feature request.

I'm going to update the README to include a blurb about updating openssl.
