### ISSUE TITLE
found an error is certificate parsing 

### ISSUE THREAD

**Issue by zivkaspersky** [aaronst/macholibre#22]
Tried to parse binary macho, sha256: `d6ecabe85f39bf1e07998afce68efa2c76c03aea715e38d13827c8643390c0f6`
Error:
```
to parse file with macholibre Traceback: 'Traceback (most recent call last):
 File "/app/static_analysis.py", line 112, in _parse_macho
 parsed_machos[sha] = parse_macho(file_path)
 File "/usr/local/lib/python3.7/site-packages/macholibre/__init__.py", line 45, in parse
 return parser.parse()
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1680, in parse
 self.parse_file()
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1671, in parse_file
 self.parse_macho(0, self.__output['size'])
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1624, in parse_macho
 self.parse_sig(offset, size, lc_codesig)
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1525, in parse_sig
 self.parse_certs(true_offset, index_offset)
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1082, in parse_certs
 subject[name] = str(value.parsed)
AttributeError: 'DirectoryString' object has no attribute 'parsed'
```

I'm not sure why you used `value.parsed` but i think `value.chosen` will fix it

**Comment by zivkaspersky** [comment]
also thanks for this lib, great job!

**Comment by aaronst** [comment]
I've fixed this, will be pushing an update soon. Thanks!
