### ISSUE TITLE
Possible error in dylib parse

### ISSUE THREAD

**Issue by zivkaspersky** [aaronst/macholibre#23]
Faield to parse macho, sha256: `a42380933ae13b0ce023b38b576f5d2c48c1c82f19033781dfbf2f3e53e19711`

Error:

```
Traceback (most recent call last):
 File "/app/static_analysis.py", line 112, in _parse_macho
 parsed_machos[sha] = parse_macho(file_path)
 File "/usr/local/lib/python3.7/site-packages/macholibre/__init__.py", line 45, in parse
 return parser.parse()
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1680, in parse
 self.parse_file()
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1671, in parse_file
 self.parse_macho(0, self.__output['size'])
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1618, in parse_macho
 lc_dysymtab=lc_dysymtab, lc_dylibs=lc_dylibs)
 File "/usr/local/lib/python3.7/site-packages/macholibre/parser.py", line 1028, in parse_imports
 dylib = lc_dylibs[dylib - 1]['name']
IndexError: list index out of range

```

**Comment by aaronst** [comment]
I'm not sure what the issue is here. There's only one dylib included in the file, so trying to grab the 14th doesn't make sense. I'll have to research a little more to figure out what it's actually trying to do. For now, it will display the number and `(OUT_OF_RANGE)`.
