### ISSUE TITLE
TypeError in parse_file

### ISSUE THREAD

**Issue by rammy22** [aaronst/macholibre#7]
``` python
Could not parse file: /sample/06e3a7cd2330d2dca49b0b9396c9601267844d7446192fcd14b03be9c40081f6
ERROR:root:Traceback (most recent call last):
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 67, in main
    parse(args.input[0], f=args.output)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 41, in parse
    p.parse_file()
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 813, in parse_file
    self.parse_macho(MachO(archive=False, offset=0, arch=identity[0],
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by aaronst** [comment]
Fixed.
