### ISSUE TITLE
ValueError in parse_requirements

### ISSUE THREAD

**Issue by rammy22** [aaronst/macholibre#9]
``` python
Could not parse file: /sample/5d4233be60ec93e8918c463790ebad305e53d2cf266ba651357d3a743f5aaab3
ERROR:root:Traceback (most recent call last):
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 67, in main
    parse(args.input[0], f=args.output)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 41, in parse
    p.parse_file()
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 814, in parse_file
    endi=identity[1], size=self.get_file_size()))
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 757, in parse_macho
    self.parse_sig(macho)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 678, in parse_sig
    self.parse_requirements(signature, offset)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 605, in parse_requirements
    magic = get_int(self.f)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/utilities.py", line 87, in get_int
    def get_int(f): return int(f.read(4).encode('hex'), 16)
ValueError: invalid literal for int() with base 16: ''
```

**Comment by aaronst** [comment]
Fixed.
